<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLeif9oD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLeif9oD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLeif9oD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLeif9oD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLeif9oD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Leif9oD',
    'container.build_id' => 'de9c874c',
    'container.build_time' => 1618509176,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLeif9oD');
